export enum ApiErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NEST_HTTP_ERROR = 'NEST_HTTP_ERROR',

  DATABASE_ERROR = 'DATABASE_ERROR',
  PRISMA_VALUE_TOO_LONG = 'PRISMA_VALUE_TOO_LONG',
  PRISMA_UNIQUE_CONSTRAINT_FAILED = 'PRISMA_UNIQUE_CONSTRAINT_FAILED',
  PRISMA_FOREIGN_KEY_FAILED = 'PRISMA_FOREIGN_KEY_FAILED',
  PRISMA_RECORD_NOT_FOUND = 'PRISMA_RECORD_NOT_FOUND',
  PRISMA_VALIDATION_ERROR = 'PRISMA_VALIDATION_ERROR',
  PRISMA_INITIALIZATION_ERROR = 'PRISMA_INITIALIZATION_ERROR',
  PRISMA_UNKNOWN_ERROR = 'PRISMA_UNKNOWN_ERROR',

  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  DUPLICATE_ENTITY = 'DUPLICATE_ENTITY',
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',
  BUSINESS_RULE_VALIDATION_FAILED = 'BUSINESS_RULE_VALIDATION_FAILED',
}
